sudo: required
services:
  - docker
before_install:
  - docker-compose build
script:
  - docker-compose exec website py.test project/test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
      secure: “$AWS_SECRET_KEY”
  region: "us-east-2"           #region要对
  app: "Collection-pro"
  env: "CollectionPro-env"
  bucket_name: "elasticbeanstalk-us-east-2-932745336105"      #到S3那里去复制
  bucket_path: "Collection-pro"
  on:
    repo: Jayden-Liang/Collection-pro
