version: '3'

services:
  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass devpassword      #默认没有密码，这里开启，密码必须和settings里的对应
    volumes:
      - 'redis:/var/lib/redis/data'
    restart: always
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -c "python:config.gunicorn" "project.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/project'
    ports:
      - '5000:5000'
    expose:
      - "5000"
    restart: always

  nginx-container:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - website



  mysql:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=devpassword
      - MYSQL_DATABASE=collection
      - MYSQL_USER=jayden
      - MYSQL_PASSWORD=devpassword

    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf'
      - 'mysqlData:/var/lib/mysql'
    restart: always

  mongo:
    image: 'mongo:3.6'
    volumes:
      - 'mongoData:/data/db'
    restart: always

  celery:
    build: .
    command: celery worker -l info -A project.blueprints.user.celery_task    #-l 可设置为info, debug,more, -A 传入包含task的那个文件
    env_file:
      - '.env'
    volumes:
      - '.:/project'
    restart: always

volumes:
  redis:
  mysqlData:
  mongoData:
